# Generated by Django 3.1 on 2020-11-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0002_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song',
            new_name='audio',
        ),
    ]
