# Generated by Django 3.1 on 2021-05-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasktodo', '0003_auto_20201106_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
